import ReactDataGrid from "@inovua/reactdatagrid-community";
import Head from "next/head";
import useSWR from "swr";
import "@inovua/reactdatagrid-community/index.css";

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const columns = [
  { name: "haksu", header: "학수번호", maxWidth: 150, defaultFlex: 1 },
  { name: "dept", header: "학부", maxWidth: 200, defaultFlex: 1 },
  { name: "name", header: "이름", defaultFlex: 1 },
  { name: "score", header: "학점", maxWidth: 80, defaultFlex: 1 },
  { name: "professor", header: "담당교수", maxWidth: 100, defaultFlex: 1 },
  { name: "status", header: "현황", defaultFlex: 1 },
];

const filterValue = [
  { name: "haksu", operator: "startsWith", type: "string", value: "" },
  { name: "dept", operator: "contains", type: "string", value: "" },
  { name: "name", operator: "contains", type: "string", value: "" },
  { name: "score", operator: "startsWith", type: "string", value: "" },
  { name: "professor", operator: "contains", type: "string", value: "" },
  { name: "status", operator: "startsWith", type: "string", value: "" },
];

const gridStyle = { minHeight: 500 };

function Grid() {
  const { data, error } = useSWR("/api/data", fetcher);

  if (data === undefined) return <></>;

  const dataSource = (data as string).split("\n").map((e) => {
    const s = e.split(",");

    return {
      haksu: s[0],
      dept: s[1],
      name: s[2],
      score: s[3],
      professor: s[4],
      status: s[5],
    };
  });

  return (
    <ReactDataGrid
      idProperty="id"
      columns={columns}
      dataSource={dataSource}
      defaultFilterValue={filterValue}
    />
  );
}

function Latest(latest: any) {
  const { data, error } = useSWR("/api/latest", fetcher);

  if (data === undefined) return <></>;

  const date = data.split("-");
  const yy = `${date[0]}년 ${date[1]}월 ${date[2]}일 ${date[3]}시 ${date[4]}분 ${date[5]}초`;

  return (
    <>
      <div style={{ margin: "10px" }}>마지막 동기화: {yy}</div>
    </>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Inha Sugang Status</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ height: "100%" }}>
        <Latest></Latest>
        <Grid></Grid>
      </main>
    </>
  );
}
